Repository IntelPython/dpctl, pull requests merged in 2020-12, with the labels that each got.

#185 Fix utils functions
  backends/CMakeLists.txt
  backends/helper/include/dppl_utils_helper.h
  backends/helper/source/dppl_utils_helper.cpp
  backends/source/dppl_sycl_device_interface.cpp
  backends/source/dppl_sycl_platform_interface.cpp
Labels: 2 - Ready to merge

#186 Fix problems in dpctl identified with Klockwork static code analysis
  backends/source/dppl_sycl_context_interface.cpp
  backends/source/dppl_sycl_platform_interface.cpp
Labels: 4 - Ready to merge

#197 Examples added
  README.md
  examples/cython/sycl_buffer/README.md
  examples/cython/sycl_buffer/_buffer_example.pyx
  examples/cython/sycl_buffer/bench.py
  examples/cython/sycl_buffer/run.py
  examples/cython/sycl_buffer/setup.py
  examples/cython/sycl_buffer/use_sycl_buffer.cpp
  examples/cython/sycl_buffer/use_sycl_buffer.h
  examples/cython/sycl_direct_linkage/_buffer_example.pyx
  examples/cython/sycl_direct_linkage/run.py
  examples/cython/sycl_direct_linkage/setup.py
  examples/cython/sycl_direct_linkage/sycl_function.cpp
  examples/cython/sycl_direct_linkage/sycl_function.hpp
  examples/cython/usm_memory/README.md
  examples/cython/usm_memory/blackscholes.pyx
  examples/cython/usm_memory/reference_black_scholes.py
  examples/cython/usm_memory/run.py
  examples/cython/usm_memory/setup.py
  examples/cython/usm_memory/sycl_blackscholes.cpp
  examples/cython/usm_memory/sycl_blackscholes.hpp
  examples/python/create_sycl_queues.py
  examples/python/usm_memory_allocation.py
  examples/python/usm_memory_host_access.py
  examples/python/usm_memory_operation.py
Labels: 3 - Waiting: author

#195 Merge gold/2021 with 0.5.0rc1
  CHANGELOG.md
  README.md
  backends/CMakeLists.txt
  backends/helper/include/dppl_utils_helper.h
  backends/helper/source/dppl_utils_helper.cpp
  backends/source/dppl_sycl_device_interface.cpp
  backends/source/dppl_sycl_platform_interface.cpp
  conda-recipe/bld.bat
  conda-recipe/build.sh
  conda-recipe/meta.yaml
  dpctl/memory/__init__.pxd
  dpctl/memory/__init__.py
  dpctl/memory/_memory.pxd
  dpctl/memory/_memory.pyx
  scripts/build_backend.py
  setup.py
Labels: 2 - Ready for Review

#225 Create expected failure test for dpctl.memory.MemoryUSMShared(np.int64(16))
  dpctl/tests/test_sycl_usm.py
Labels: 4 - Ready to merge

#226 Update docs generation instruction
  docs/README.md
Labels: documentation

#222 Update CHANGELOG
  CHANGELOG.md
Labels: 3 - Waiting: reviewer

#234 Fix incorrect import in the cython example.
  examples/cython/usm_memory/run.py
Labels: 3 - Waiting: reviewer
