Repository IntelPython/dpctl, pull requests merged in 2021-08, with the labels that each got.

#518 Run tests on Gen9
  .github/workflows/conda-package.yml
Labels: infrastructure

#516 Add a new DPCTLEvent_GetCommandExecutionStatus function
  dpctl-capi/helper/include/dpctl_utils_helper.h
  dpctl-capi/helper/source/dpctl_utils_helper.cpp
  dpctl-capi/include/dpctl_sycl_enum_types.h
  dpctl-capi/include/dpctl_sycl_event_interface.h
  dpctl-capi/source/dpctl_sycl_event_interface.cpp
  dpctl-capi/tests/test_sycl_event_interface.cpp
Labels: 4 - Ready to merge

#519 Add 3 new functions for sycl::event::get_profiling_info
  dpctl-capi/include/dpctl_sycl_event_interface.h
  dpctl-capi/source/dpctl_sycl_event_interface.cpp
  dpctl-capi/tests/test_sycl_event_interface.cpp
Labels: 4 - Ready to merge

#510 Add a new DPCTLEvent_GetWaitList function
  dpctl-capi/include/dpctl_sycl_event_interface.h
  dpctl-capi/source/dpctl_sycl_event_interface.cpp
  dpctl-capi/tests/test_sycl_event_interface.cpp
Labels: 1 - In Progress
