Repository IntelPython/dpctl, pull requests merged in 2021-11, with the labels that each got.

#644 Fix public CI
  .github/workflows/conda-package.yml
Labels: infrastructure

#580 Use renamed DPC++ runtime package `dpcpp-cpp-rt`
  conda-recipe/meta.yaml
Labels: infrastructure, build

#678 Extending `dpctl.device_context` with nested contexts
  CHANGELOG.md
  dpctl/__init__.py
  dpctl/_sycl_queue_manager.pyx
  dpctl/tests/test_sycl_queue_manager.py
Labels: enhancement, numba-dppy

#699 Set the last byte in allocated char array to zero [cherry picked from #650]
  CHANGELOG.md
  dpctl-capi/helper/include/dpctl_string_utils.hpp
Labels: bug
