Repository IntelPython/dpctl, pull requests merged in 2021-07, with the labels that each got.

#504 Add a new DPCTLEvent_Copy function
  dpctl-capi/include/dpctl_sycl_event_interface.h
  dpctl-capi/source/dpctl_sycl_event_interface.cpp
  dpctl-capi/tests/test_sycl_event_interface.cpp
Labels: 2 - Ready for Review

#511 Add tests for DPCTLEvent_Wait
  dpctl-capi/source/dpctl_sycl_event_interface.cpp
  dpctl-capi/tests/test_sycl_event_interface.cpp
Labels: 1 - In Progress

#514 Use dpcpp compiler package for Linux
  conda-recipe/build.sh
  conda-recipe/meta.yaml
Labels: build, infrastructure

#515 Conda package CI pipeline on GitHub Actions
  .github/workflows/conda-package.yml
Labels: build, infrastructure
